CREATE TABLE ONETOMANYBIDIRECTIONAL_DEPARTMENT (ID INTEGER  NOT NULL AUTO_INCREMENT,
                         NAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE ONETOMANYBIDIRECTIONAL_EMPLOYEE (ID INTEGER  NOT NULL AUTO_INCREMENT,
                       NAME VARCHAR(255), SALARY BIGINT,
                       ONETOMANYBIDIRECTIONAL_DEPARTMENT_ID INTEGER, PRIMARY KEY (ID),
                       CONSTRAINT ONETOMANYBIDIRECTIONAL_DEPT_FK FOREIGN KEY (ONETOMANYBIDIRECTIONAL_DEPARTMENT_ID) REFERENCES ONETOMANYBIDIRECTIONAL_DEPARTMENT (ID));