CREATE TABLE EMBEDDABLEKEYMAPPING_EMPLOYEE (ID INTEGER AUTO_INCREMENT NOT NULL, F_NAME VARCHAR(255), L_NAME VARCHAR(255), SALARY BIGINT,
                                            DEPARTMENT_ID INTEGER, PRIMARY KEY (ID));
CREATE TABLE EMBEDDABLEKEYMAPPING_DEPARTMENT (ID INTEGER AUTO_INCREMENT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID));