CREATE TABLE LISTONETOMANYDEPARTMENT (ID INTEGER  NOT NULL AUTO_INCREMENT,
                                      NAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE LISTONETOMANYEMPLOYEE (ID INTEGER  NOT NULL AUTO_INCREMENT,
                                    NAME VARCHAR(255), SALARY BIGINT,
                                    LISTONETOMANYDEPARTMENT_ID INTEGER, PRIMARY KEY (ID),
  CONSTRAINT DEPT_FK FOREIGN KEY (LISTONETOMANYDEPARTMENT_ID) REFERENCES LISTONETOMANYDEPARTMENT (ID));