CREATE TABLE ELEMENTCOLLECTIONENUMMAP_EMP_PHONE (Employee_ID INTEGER NOT NULL, PHONE_NUM VARCHAR(255), PHONE_TYPE VARCHAR(255));
CREATE TABLE ELEMENTCOLLECTIONENUMMAP_EMPLOYEE (ID INTEGER auto_increment NOT NULL, NAME VARCHAR(255), SALARY BIGINT, DEPARTMENT_ID INTEGER, PRIMARY KEY (ID));
CREATE TABLE ELEMENTCOLLECTIONENUMMAP_DEPARTMENT (ID INTEGER auto_increment NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID));
ALTER TABLE ELEMENTCOLLECTIONENUMMAP_EMP_PHONE ADD CONSTRAINT EMPPHONEID FOREIGN KEY (Employee_ID) REFERENCES ELEMENTCOLLECTIONENUMMAP_EMPLOYEE (ID);
ALTER TABLE ELEMENTCOLLECTIONENUMMAP_EMPLOYEE ADD CONSTRAINT MPLOYEEDPARTMENTID FOREIGN KEY (DEPARTMENT_ID) REFERENCES ELEMENTCOLLECTIONENUMMAP_DEPARTMENT (ID);