CREATE TABLE MANYTOMANYMAP_EMPLOYEE (ID INTEGER AUTO_INCREMENT NOT NULL, NAME VARCHAR(255), SALARY BIGINT, PRIMARY KEY (ID));
CREATE TABLE MANYTOMANYMAP_DEPARTMENT (ID INTEGER AUTO_INCREMENT NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE MANYTOMANYMAP_DEPT_EMP (DEPT_ID INTEGER NOT NULL, EMP_ID INTEGER NOT NULL, CUB_ID VARCHAR(255), PRIMARY KEY (DEPT_ID, EMP_ID));