CREATE TABLE MANYTOMANYBIDIRECTIONAL_PROJECT (ID INTEGER  NOT NULL AUTO_INCREMENT,
                      NAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE MANYTOMANYBIDIRECTIONAL_EMPLOYEE (ID INTEGER  NOT NULL AUTO_INCREMENT,
                       NAME VARCHAR(255), SALARY BIGINT, PRIMARY KEY (ID));
CREATE TABLE MANYTOMANYBIDIRECTIONAL_EMPLOYEE__PROJECT (MANYTOMANYBIDIRECTIONAL_PROJECTS_ID INTEGER NOT NULL, MANYTOMANYBIDIRECTIONAL_EMPLOYEES_ID INTEGER NOT NULL,
                               CONSTRAINT MANYTOMANYBIDIRECTIONAL_PROJECTS_FK FOREIGN KEY (MANYTOMANYBIDIRECTIONAL_PROJECTS_ID) REFERENCES MANYTOMANYBIDIRECTIONAL_PROJECT (ID),
                               CONSTRAINT MANYTOMANYBIDIRECTIONAL_EMPLOYEES_FK FOREIGN KEY (MANYTOMANYBIDIRECTIONAL_EMPLOYEES_ID) REFERENCES MANYTOMANYBIDIRECTIONAL_EMPLOYEE (ID),
                               PRIMARY KEY (MANYTOMANYBIDIRECTIONAL_PROJECTS_ID, MANYTOMANYBIDIRECTIONAL_EMPLOYEES_ID))