CREATE TABLE ONETOMANYMAP_EMPLOYEE (ID INTEGER auto_increment NOT NULL, NAME VARCHAR(255), SALARY BIGINT,
                       CUB_ID VARCHAR(255), DEPARTMENT_ID INTEGER, PRIMARY KEY (ID));
CREATE TABLE ONETOMANYMAP_DEPARTMENT (ID INTEGER auto_increment NOT NULL, NAME VARCHAR(255), PRIMARY KEY (ID));